# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(278, 114)
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(100, 20, 81, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.btnReject = QtWidgets.QPushButton(Dialog)
        self.btnReject.setGeometry(QtCore.QRect(100, 70, 81, 31))
        self.btnReject.setObjectName("btnReject")
        self.btnDone = QtWidgets.QPushButton(Dialog)
        self.btnDone.setGeometry(QtCore.QRect(190, 70, 81, 31))
        self.btnDone.setDefault(False)
        self.btnDone.setObjectName("btnDone")
        self.btnAccept = QtWidgets.QPushButton(Dialog)
        self.btnAccept.setGeometry(QtCore.QRect(10, 70, 81, 31))
        self.btnAccept.setDefault(False)
        self.btnAccept.setObjectName("btnAccept")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnOk.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnReject.setText(_translate("Dialog", "reject()"))
        self.btnDone.setText(_translate("Dialog", "done()"))
        self.btnAccept.setText(_translate("Dialog", "accept()"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
