# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(189, 231)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblNick = QtWidgets.QLabel(Dialog)
        self.lblNick.setObjectName("lblNick")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblNick)
        self.editNick = QtWidgets.QLineEdit(Dialog)
        self.editNick.setObjectName("editNick")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editNick)
        self.verticalLayout.addLayout(self.formLayout)
        self.groupGender = QtWidgets.QGroupBox(Dialog)
        self.groupGender.setObjectName("groupGender")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupGender)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rdoMale = QtWidgets.QRadioButton(self.groupGender)
        self.rdoMale.setChecked(True)
        self.rdoMale.setObjectName("rdoMale")
        self.horizontalLayout.addWidget(self.rdoMale)
        self.rdoFemale = QtWidgets.QRadioButton(self.groupGender)
        self.rdoFemale.setObjectName("rdoFemale")
        self.horizontalLayout.addWidget(self.rdoFemale)
        self.verticalLayout.addWidget(self.groupGender)
        self.groupHobby = QtWidgets.QGroupBox(Dialog)
        self.groupHobby.setCheckable(False)
        self.groupHobby.setObjectName("groupHobby")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupHobby)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chkHobby1 = QtWidgets.QCheckBox(self.groupHobby)
        self.chkHobby1.setObjectName("chkHobby1")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.chkHobby1)
        self.verticalLayout_2.addWidget(self.chkHobby1)
        self.chkHobby2 = QtWidgets.QCheckBox(self.groupHobby)
        self.chkHobby2.setObjectName("chkHobby2")
        self.buttonGroup.addButton(self.chkHobby2)
        self.verticalLayout_2.addWidget(self.chkHobby2)
        self.chkHobby3 = QtWidgets.QCheckBox(self.groupHobby)
        self.chkHobby3.setObjectName("chkHobby3")
        self.buttonGroup.addButton(self.chkHobby3)
        self.verticalLayout_2.addWidget(self.chkHobby3)
        self.verticalLayout.addWidget(self.groupHobby)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblNick.setText(_translate("Dialog", "닉네임"))
        self.groupGender.setTitle(_translate("Dialog", "성별"))
        self.rdoMale.setText(_translate("Dialog", "남성"))
        self.rdoFemale.setText(_translate("Dialog", "여성"))
        self.groupHobby.setTitle(_translate("Dialog", "취미"))
        self.chkHobby1.setText(_translate("Dialog", "낚시"))
        self.chkHobby2.setText(_translate("Dialog", "서핑"))
        self.chkHobby3.setText(_translate("Dialog", "여행"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
