# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(185, 134)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.editName = QtWidgets.QLineEdit(self.centralwidget)
        self.editName.setObjectName("editName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editName)
        self.verticalLayout.addLayout(self.formLayout)
        self.lblNick = QtWidgets.QLabel(self.centralwidget)
        self.lblNick.setObjectName("lblNick")
        self.verticalLayout.addWidget(self.lblNick)
        self.lblGender = QtWidgets.QLabel(self.centralwidget)
        self.lblGender.setObjectName("lblGender")
        self.verticalLayout.addWidget(self.lblGender)
        self.lblHobby = QtWidgets.QLabel(self.centralwidget)
        self.lblHobby.setObjectName("lblHobby")
        self.verticalLayout.addWidget(self.lblHobby)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 185, 20))
        self.menubar.setObjectName("menubar")
        self.menuPersonal = QtWidgets.QMenu(self.menubar)
        self.menuPersonal.setObjectName("menuPersonal")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHobby = QtWidgets.QAction(MainWindow)
        self.actionHobby.setObjectName("actionHobby")
        self.menuPersonal.addAction(self.actionHobby)
        self.menubar.addAction(self.menuPersonal.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblName.setText(_translate("MainWindow", "이름 :"))
        self.lblNick.setText(_translate("MainWindow", "닉네임 표시"))
        self.lblGender.setText(_translate("MainWindow", "성별표시"))
        self.lblHobby.setText(_translate("MainWindow", "취미표시"))
        self.menuPersonal.setTitle(_translate("MainWindow", "Personal"))
        self.actionHobby.setText(_translate("MainWindow", "Hobby"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
