# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyDialog(object):
    def setupUi(self, MyDialog):
        MyDialog.setObjectName("MyDialog")
        MyDialog.resize(375, 232)
        MyDialog.setStyleSheet("QGroupBox {\n"
"    border: 2px solid rgb(182,182,182);\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    left: 10px;\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(MyDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblName = QtWidgets.QLabel(self.layoutWidget)
        self.lblName.setObjectName("lblName")
        self.verticalLayout.addWidget(self.lblName)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 30, 281, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkFishing = QtWidgets.QCheckBox(self.layoutWidget1)
        self.chkFishing.setObjectName("chkFishing")
        self.horizontalLayout_2.addWidget(self.chkFishing)
        self.chkSurfing = QtWidgets.QCheckBox(self.layoutWidget1)
        self.chkSurfing.setObjectName("chkSurfing")
        self.horizontalLayout_2.addWidget(self.chkSurfing)
        self.chkTraveling = QtWidgets.QCheckBox(self.layoutWidget1)
        self.chkTraveling.setObjectName("chkTraveling")
        self.horizontalLayout_2.addWidget(self.chkTraveling)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnOK = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_3.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(MyDialog)
        QtCore.QMetaObject.connectSlotsByName(MyDialog)

    def retranslateUi(self, MyDialog):
        _translate = QtCore.QCoreApplication.translate
        MyDialog.setWindowTitle(_translate("MyDialog", "Dialog"))
        self.lblName.setText(_translate("MyDialog", "Name: unknown"))
        self.groupBox_2.setTitle(_translate("MyDialog", "Hobby"))
        self.chkFishing.setText(_translate("MyDialog", "Fishing"))
        self.chkSurfing.setText(_translate("MyDialog", "Surfing"))
        self.chkTraveling.setText(_translate("MyDialog", "Traveling"))
        self.btnOK.setText(_translate("MyDialog", "OK"))
        self.btnCancel.setText(_translate("MyDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyDialog = QtWidgets.QDialog()
    ui = Ui_MyDialog()
    ui.setupUi(MyDialog)
    MyDialog.show()
    sys.exit(app.exec_())
